apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      confluent-platform: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: prometheus
