---
# tasks file for confluent.control_center-setup
 name: Create confluent control center directory for BASIC auth
  file:
    path: /tmp/confluent
    state: directory
    owner: cp-control-center
    group: confluent
    mode: '0755'
- name: setup the confluent-control center BASIC AUTH
  template:
    src: basic-auth.j2
    dest: /tmp/confluent/login.properties
    owner: cp-control-center
    group: confluent
    mode: '0744'
