---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pageviews
  namespace: kafka-sasl-ssl-user
spec:
  replicas: 3
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential
---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: datagen-local-01
  namespace:  kafka-sasl-ssl-user
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 2
  connectClusterRef:
    name: connect
  connectRest:
    authentication:
      type: bearer
      bearer:
        secretRef: connect-mds-client
  configs:
    kafka.topic: "pageviews"
    quickstart: "pageviews"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    max.interval: "100"
    iterations: "10000000"
