all:
  vars:
    ansible_connection: ssh
    ansible_user: admin
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_gcloud
    ansible_check_mode: True

ldap:
  hosts:
    ldap0.gcp.cp.com:
      openldap_base: "dc=confluent,dc=io"
      openldap_org: "confluent"
      openldap_tld: "io"
      openldap_config: true
  vars:
    openldap_populate: true
    openldap_posixgroups:
      - name: miners
        ou: Groups
        gidNum: 5000
      - name: kafka
        ou: Groups
        gidNum: 5001
    openldap_users:
      - FirstName: John
        LastName: Smith
        ou: People
        uidNum: 10000
        gidNum: 5000
        password: P@55w0rd
        loginShell: /bin/bash
        homeDirectory: /home/john
      - FirstName: Professor
        LastName: Farnsworth
        ou: People
        uidNum: 10001
        gidNum: 5001
        password: professor
        loginShell: /bin/bash
        homeDirectory: /home/professor
      - FirstName: Bender
        LastName: Robot
        ou: People
        uidNum: 10002
        gidNum: 5001
        password: bender
        loginShell: /bin/bash
        homeDirectory: /home/bender
      - FirstName: Fry
        LastName: Philip
        ou: People
        uidNum: 10003
        gidNum: 5001
        password: fry
        loginShell: /bin/bash
        homeDirectory: /home/fry
