apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: cp-super
  labels:
    strimzi.io/cluster: cflt
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    # Kafka Connects internal topics used to store configuration, offsets or status
    - resource:
        type: cluster
        name: cflt
      operation: Alter
