apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: kafka
  namespace: cfksaslplain
spec:
  kafkaRest:
    authentication:
      type: basic
      bearer:
        secretRef: basic-client
